name: gerenciador-academico
version: '1.0.0'
summary: Aplicativo de gerenciamento acadêmico
description: Aplicação JavaFX integrada ao Google Sheets.

grade: stable
confinement: strict
base: core22

apps:
  gerenciador-academico:
    command: launch-gerenciador-academico
    plugs: [network, desktop, desktop-legacy, wayland, x11]

parts:
  gerenciador-academico:
    plugin: dump
    source: snap/local/
    stage:
      - bin/projetofinal-1.0.0.jar
      - launch-gerenciador-academico
