name: gerenciador-academico
version: '1.0.0'
summary: Aplicativo JavaFX de Gerenciamento Acadêmico
description: |
  Projeto final de POO usando JavaFX e integração com Google Sheets.

grade: stable
confinement: strict
base: core22

apps:
  gerenciador-academico:
    command: launch-gerenciador-academico
    plugs: [ network, desktop, desktop-legacy, wayland, x11 ]

parts:
  gerenciador-academico:
    plugin: dump
    source: snap/
    stage:
      - launch-gerenciador-academico
      - bin/projetofinal-1.0.0.jar
