name: Build Installers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Create credentials.json from base64 secret
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" | base64 -d > src/main/resources/credentials.json

      - name: Check JSON output (debug)
        run: |
          head -n 10 src/main/resources/credentials.json

      - name: Install fpm
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm

      - name: Build fat jar
        run: ./gradlew clean jar

      - name: Package with fpm (com dependência openjfx e .desktop)
        run: |
          mkdir -p package/usr/local/gerenciador-academico
          cp build/libs/*.jar package/usr/local/gerenciador-academico/
          cp src/main/resources/credentials.json package/usr/local/gerenciador-academico/

          mkdir -p package/usr/bin
          echo '#!/bin/bash
          java --module-path /usr/share/openjfx/lib --add-modules javafx.controls,javafx.fxml -jar /usr/local/gerenciador-academico/projetofinal-1.0.0.jar' > package/usr/bin/gerenciador-academico
          chmod +x package/usr/bin/gerenciador-academico

          mkdir -p package/usr/share/applications
          cat > package/usr/share/applications/gerenciador-academico.desktop <<EOF
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=Gerenciador Acadêmico
          Comment=Gerenciador Acadêmico JavaFX
          Exec=/usr/bin/gerenciador-academico
          Icon=/usr/share/icons/gerenciador-academico.png
          Terminal=false
          Categories=Education;Utility;
          StartupNotify=true
          EOF

          mkdir -p package/usr/share/icons
          cp src/main/resources/icon.png package/usr/share/icons/gerenciador-academico.png

          fpm -s dir -t deb \
              -n gerenciador-academico \
              -v 1.0.0 \
              --depends openjfx \
              --depends openjdk-17-jre \
              -C package .
  

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build fat jar
        run: ./gradlew clean jar

      - name: Package with jpackage (Windows)
        run: ./gradlew createInstaller -PinstallerType=msi

      - name: Upload .msi installer
        uses: actions/upload-artifact@v4
        with:
          name: gerenciador-academico-msi
          path: build/installer/*.msi

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build fat jar
        run: ./gradlew clean jar

      - name: Package with jpackage (macOS)
        run: ./gradlew createInstaller -PinstallerType=pkg

      - name: Upload .pkg installer
        uses: actions/upload-artifact@v4
        with:
          name: gerenciador-academico-pkg
          path: build/installer/*.pkg
