name: Build Installers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install fpm
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm

      - name: Build fat jar
        run: ./gradlew clean jar

      - name: Package with fpm (com dependência openjfx)
        run: |
          mkdir -p package/usr/local/gerenciador-academico
          cp build/libs/*.jar package/usr/local/gerenciador-academico/

          fpm -s dir -t deb \
              -n gerenciador-academico \
              -v 1.0.0 \
              --depends openjfx \
              --depends openjdk-17-jre \
              -C package .

      - name: Upload .deb installer
        uses: actions/upload-artifact@v4
        with:
          name: gerenciador-academico-deb
          path: "*.deb"

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build fat jar
        run: ./gradlew clean jar

      - name: Package with jpackage (Windows)
        run: ./gradlew createInstaller -PinstallerType=msi

      - name: Upload .msi installer
        uses: actions/upload-artifact@v4
        with:
          name: gerenciador-academico-msi
          path: build/installer/*.msi

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build fat jar
        run: ./gradlew clean jar

      - name: Package with jpackage (macOS)
        run: ./gradlew createInstaller -PinstallerType=pkg

      - name: Upload .pkg installer
        uses: actions/upload-artifact@v4
        with:
          name: gerenciador-academico-pkg
          path: build/installer/*.pkg
