name: Java Build & Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Create credentials.json
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

      - name: Build Project
        run: ./gradlew clean build

      - name: Package with jpackage
        run: |
          mkdir -p dist

          jpackage \
            --type ${{ matrix.os == 'windows-latest' && 'exe' || matrix.os == 'ubuntu-latest' && 'deb' || 'pkg' }} \
            --input build/libs \
            --dest dist \
            --name MeuApp \
            --main-jar nome-do-seu-jar.jar \
            --main-class projetofinal.model.Main \
            --java-options "--enable-preview" \
            --verbose

        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MeuApp-${{ matrix.os }}
          path: dist/*
